--// File generated by F0x's Resources Generator 3.0.0 \\--

if ( SERVER ) then
	resource.AddFile( "materials/effects/flashlight/flashlight001_l4d2.vmt" )
	resource.AddFile( "materials/effects/flashlight/flashlight001_l4d2.vtf" )
	resource.AddFile( "materials/effects/flashlight/flashlight001_ronster.vmt" )
	resource.AddFile( "materials/effects/flashlight/flashlight001_ronster.vtf" )
	resource.AddFile( "materials/effects/flashlight/flashlight_horrible.vmt" )
	resource.AddFile( "materials/effects/flashlight/flashlight_horrible.vtf" )
	resource.AddFile( "materials/effects/flashlight/flashlight_led.vmt" )
	resource.AddFile( "materials/effects/flashlight/flashlight_led.vtf" )
	resource.AddFile( "materials/effects/flashlight/flashlight_trinity.vmt" )
	resource.AddFile( "materials/effects/flashlight/flashlight_trinity.vtf" )
	resource.AddFile( "materials/models/weapons/flashlight_zm/flashlight_diffuse.vmt" )
	resource.AddFile( "materials/models/weapons/flashlight_zm/flashlight_diffuse.vtf" )
	resource.AddFile( "materials/models/weapons/flashlight_zm/flashlight_diffuse_normal.vtf" )
	resource.AddFile( "materials/weapons/weapon_flashlight.vmt" )
	resource.AddFile( "materials/weapons/weapon_flashlight.vtf" )
	resource.AddFile( "materials/weapons/weapon_flashlight_kill.vmt" )
	resource.AddFile( "materials/weapons/weapon_flashlight_kill.vtf" )
	resource.AddFile( "models/weapons/c_flashlight_zm.mdl" )
	resource.AddFile( "models/weapons/w_flashlight_zm.mdl" )
end