
/*
RESEARCHERMODELS = {
"models/player/kerry/class_scientist_1.mdl",
"models/player/kerry/class_scientist_2.mdl",
"models/player/kerry/class_scientist_3.mdl",
"models/player/kerry/class_scientist_4.mdl",
"models/player/kerry/class_scientist_5.mdl",
"models/player/kerry/class_scientist_6.mdl",
"models/player/kerry/class_scientist_7.mdl",
}
*/
RESEARCHERMODELS = {
"models/bmscientistcits/p_female_01.mdl",
"models/bmscientistcits/p_female_02.mdl",
"models/bmscientistcits/p_female_03.mdl",
"models/bmscientistcits/p_female_04.mdl",
"models/bmscientistcits/p_female_06.mdl",
"models/bmscientistcits/p_female_07.mdl",
"models/bmscientistcits/p_male_01.mdl",
"models/bmscientistcits/p_male_02.mdl",
"models/bmscientistcits/p_male_03.mdl",
"models/bmscientistcits/p_male_04.mdl",
"models/bmscientistcits/p_male_05.mdl",
"models/bmscientistcits/p_male_06.mdl",
"models/bmscientistcits/p_male_07.mdl",
"models/bmscientistcits/p_male_08.mdl",
"models/bmscientistcits/p_male_09.mdl",
"models/bmscientistcits/p_male_10.mdl",
}
CHAOSMODELS = {
"models/kerry/merriweather1.mdl",
"models/kerry/merriweather2.mdl",
"models/kerry/merriweather3.mdl",
"models/kerry/merriweather4.mdl",
"models/kerry/merriweather5.mdl",
"models/kerry/merriweather6.mdl",
"models/kerry/merriweather7.mdl",
"models/kerry/merriweather8.mdl",
}
SECURITYMODELS = {
"models/player/group04/male_01.mdl",
"models/player/group04/male_02.mdl",
"models/player/group04/male_03.mdl",
"models/player/group04/male_04.mdl",
"models/player/group04/male_05.mdl",
"models/player/group04/male_06.mdl",
"models/player/group04/male_07.mdl",
"models/player/group04/male_08.mdl",
"models/player/group04/male_09.mdl",
}
CLASSDMODELS = {
"models/player/kerry/class_d_1.mdl",
"models/player/kerry/class_d_2.mdl",
"models/player/kerry/class_d_3.mdl",
"models/player/kerry/class_d_4.mdl",
"models/player/kerry/class_d_5.mdl",
"models/player/kerry/class_d_6.mdl",
"models/player/kerry/class_d_7.mdl",
}

ALLCLASSES = {
	classds = {
		name = "Class D Personell",
		color = Color(255, 130, 0),
		roles = {
			{name = ROLES.ROLE_CLASSD,
			 team = TEAM_CLASSD,
			 weapons = {"br_holster", "br_id"},
			 showweapons = {},
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = CLASSDMODELS,
			 showmodel = nil,
			 level = 0,
			 customcheck = nil,
			 flashlight = false,
			 max = 64
			},
			{name = ROLES.ROLE_VETERAN,
			 team = TEAM_CLASSD,
			 weapons = {"br_holster", "br_id"},
			 showweapons = {},
			 ammo = {},
			 health = 120,
			 armor = 0,
			 walkspeed = 1.1,
			 runspeed = 1.1,
			 jumppower = 1.1,
			 vest = nil,
			 models = CLASSDMODELS,
			 showmodel = nil,
			 flashlight = false,
			 level = 6,
			 max = 4
			}
		}
	},
	researchers = {
		name = "Unarmed Site Staff",
		color = Color(66, 188, 244),
		roles = {
			{name = ROLES.ROLE_RES,
			 team = TEAM_SCI,
			 weapons = {"br_holster", "br_id", "keycard_level2"},
			 showweapons = {"Keycard Level 2"},
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = RESEARCHERMODELS,
			 showmodel = nil,
			 flashlight = true,
			 level = 0,
			 max = 36
			},
			{name = ROLES.ROLE_MEDIC,
			 team = TEAM_SCI,
			 weapons = {"br_holster", "br_id", "keycard_level2", "item_ultramedkit"},
			 showweapons = {"Keycard Level 2", "Med Kit"},
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = RESEARCHERMODELS,
			 showmodel = nil,
			 flashlight = true,
			 level = 1,
			 max = 4
			}
		}
	},
	security = {
		name = "Armed Site Security",
		color = Color(0, 100, 255),
		roles = {
			{name = ROLES.ROLE_SECURITY,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_level2", "item_radio", "weapon_stunstick", "weapon_mtf_tmp"},
			 showweapons = {"Keycard Level 2", "Radio", "Stunstick", "TMP"},
			 ammo = {{"SMG1", 200}},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.9,
			 runspeed = 0.95,
			 jumppower = 0.9,
			 vest = "armor_security",
			 models = RESEARCHERMODELS,
			 showmodel = SECURITYMODELS[1],
			 pmcolor = nil,
			 flashlight = true,
			 level = 0,
			 max = 24,
			 sorting = 0,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_CSECURITY,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_level4", "item_radio", "item_cameraview", "weapon_stunstick", "weapon_mtf_p90"},
			 showweapons = {"Keycard Level 4", "Radio", "Camera View", "Stunstick", "P90"},
			 ammo = {{"SMG1", 200}},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.9,
			 runspeed = 0.95,
			 jumppower = 0.9,
			 vest = "armor_security",
			 models = RESEARCHERMODELS,
			 showmodel = SECURITYMODELS[1],
			 pmcolor = nil,
			 flashlight = true,
			 level = 4,
			 max = 1,
			 sorting = 6,
			 importancelevel = 2
			},
			{name = ROLES.ROLE_MTFGUARD,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_level3", "item_radio", "weapon_stunstick", "weapon_mtf_ump45"},
			 showweapons = {"Keycard Level 3", "Radio", "Stunstick", "UMP"},
			 ammo = {{"SMG1", 200}},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.85,
			 runspeed = 0.92,
			 jumppower = 0.87,
			 vest = "armor_mtfguard",
			 models = RESEARCHERMODELS,
			 showmodel = "models/mtf/mtf remasteredhd.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 2,
			 max = 12,
			 sorting = 1,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_CHAOSSPY,
			 team = TEAM_CHAOS,
			 weapons = {"br_holster", "br_id", "keycard_level3", "item_radio", "weapon_stunstick", "weapon_mtf_ump45"},
			 showweapons = {"Keycard Level 3", "Radio", "Stunstick", "UMP"},
			 ammo = {{"SMG1", 200}},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.85,
			 runspeed = 0.92,
			 jumppower = 0.87,
			 vest = "armor_mtfguard",
			 models = RESEARCHERMODELS,
			 showmodel = "models/mtf/mtf remasteredhd.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 3,
			 max = 2,
			 sorting = 2,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_MTFMEDIC,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_level3", "item_radio", "item_ultramedkit", "weapon_stunstick", "weapon_mtf_ump45"},
			 showweapons = {"Keycard Level 3", "Radio", "Medkit", "Stunstick", "UMP"},
			 ammo = {{"SMG1", 200}},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.85,
			 runspeed = 0.92,
			 jumppower = 0.87,
			 vest = "armor_mtfmedic",
			 models = RESEARCHERMODELS,
			 showmodel = "models/payday2/units/medic_player.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 5,
			 max = 1,
			 sorting = 3,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_MTFL,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_level4", "item_radio", "item_nvg", "item_cameraview", "weapon_stunstick", "weapon_chaos_famas"},
			 showweapons = {"Keycard Level 4", "Radio", "NVG", "Camera View", "Stunstick", "FAMAS"},
			 ammo = {{"AR2", 200}},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.87,
			 runspeed = 0.94,
			 jumppower = 0.9,
			 vest = "armor_mtfl",
			 models = RESEARCHERMODELS,
			 showmodel = "models/mw2/skin_04/mw2_soldier_04.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 3,
			 max = 2,
			 sorting = 4,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_HAZMAT,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_level4", "item_radio", "item_nvg", "item_cameraview", "weapon_stunstick", "weapon_chaos_m249"},
			 showweapons = {"Keycard Level 4", "Radio", "NVG", "Camera View", "Stunstick", "M249"},
			 ammo = {{"AR2", 600}},
			 health = 125,
			 armor = 50,
			 walkspeed = 0.93,
			 runspeed = 0.98,
			 jumppower = 0.92,
			 vest = "armor_hazmat",
			 models = RESEARCHERMODELS,
			 showmodel = "models/player/hazmat/hazmat1980.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 8,
			 max = 3,
			 sorting = 5,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_MTFCOM,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_level4", "item_radio", "item_nvg", "item_cameraview", "weapon_stunstick", "weapon_mtf_mp5"},
			 showweapons = {"Keycard Level 4", "Radio", "NVG", "Camera View", "Stunstick", "MP5"},
			 ammo = {{"SMG1", 200}},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.9,
			 runspeed = 0.94,
			 jumppower = 0.9,
			 vest = "armor_mtfcom",
			 models = RESEARCHERMODELS,
			 showmodel = "models/mtf/mtf remasteredhd.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 5,
			 max = 1,
			 sorting = 7,
			 importancelevel = 3
			},
			{name = ROLES.ROLE_SD,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_level5", "item_radio", "item_cameraview", "weapon_stunstick", "weapon_mtf_deagle"},
			 showweapons = {"Keycard Level 5", "Radio", "Camera View", "Stunstick", "Desert Eagle"},
			 ammo = {{"Pistol", 105}},
			 health = 100,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = {"models/player/breen.mdl"},
			 showmodel = "models/player/breen.mdl",
			 pmcolor = Color(0,0,0),
			 flashlight = true,
			 level = 6,
			 max = 1,
			 sorting = 8,
			 importancelevel = 4
			},
		}
	},
	support = {
		name = "Armed Site Support",
		color = Color(29, 81, 56),
		roles = {
			{name = ROLES.ROLE_MTFNTF,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_level4", "item_radio", "item_nvg", "weapon_stunstick", "weapon_chaos_famas"},
			 showweapons = {"Keycard Level 4", "Radio", "NVG", "Stunstick", "FAMAS"},
			 ammo = {{"AR2", 180}},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.86,
			 runspeed = 0.93,
			 jumppower = 0.85,
			 vest = "armor_ntf",
			 models = RESEARCHERMODELS,
			 showmodel = "models/player/pmc_4/pmc__07.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 3,
			 max = 3
			},
			{name = ROLES.ROLE_CHAOS,
			 team = TEAM_CHAOS,
			 weapons = {"br_holster", "br_id", "keycard_level4", "item_radio", "weapon_stunstick", "weapon_chaos_ak47"},
			 showweapons = {"Keycard Level 4", "Radio", "Stunstick", "AK47"},
			 ammo = {{"AR2", 180}},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.86,
			 runspeed = 0.93,
			 jumppower = 0.85,
			 vest = "armor_chaosins",
			 models = CHAOSMODELS,
			 showmodel = "models/friskiukas/bf4/us_01.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 4,
			 max = 3
			}
		}
	}
}
