--// File generated by F0x's Resources Generator 3.0.0 \\--

if ( SERVER ) then
	resource.AddFile( "materials/models/vinrax/props/513.vmt" )
	resource.AddFile( "materials/models/vinrax/props/513.vtf" )
	resource.AddFile( "materials/scp_pack/scp513.png" )
	resource.AddFile( "materials/vgui/entities/scp-513.vmt" )
	resource.AddFile( "materials/vgui/entities/scp-513.vtf" )
	resource.AddFile( "models/vinrax/props/scp_513.mdl" )
	resource.AddFile( "sound/scp_pack/bell1.ogg" )
	resource.AddFile( "sound/scp_pack/bell2.ogg" )
	resource.AddFile( "sound/scp_pack/horror1.ogg" )
	resource.AddFile( "sound/scp_pack/horror2.ogg" )
end